### PR TITLE
add magicVar api

### PR DESCRIPTION
**Pull request by gf53520**
## Changes
   
  - [ ] add magicVar api

 
## Reviewers

  - [x] @wonderflow  please review
    
## Checklist
   
   - [ ] Rebased/mergable
   - [ ] Tests pass
   - [ ] CHANGELOG.md updated
   - [ ] Jira issue/task done

### CODE REVIEW

**Comment by wonderflow** [comment]
这个缓姐有利用上写点case吗，放在kirk的集成测试上

**Comment by DeliaWang** [comment]
Q4会补充离线计算的集成测试

**Comment by wonderflow** [comment]
LGTM

**Comment by gf53520** [comment]
apiserver集成测试有的

**Pull request merged**
